### ISSUE TITLE
iso690-numeric-sk throws AttributeError

### ISSUE THREAD

**Issue by Dreamsorcerer** [brechtm/citeproc-py#100]
Seems our users are giving this library a thorough testing. :P

```
>>> import citeproc as c
>>> import citeproc_styles as cs
>>> s = c.CitationStylesStyle(cs.get_style_filepath("iso690-numeric-sk"))
>>> r = {'type': 'article', 'id': 'ref0', 'title': None, 'DOI': '10.1271/kagakutoseibutsu.51.483', 'author': [{'family': 'Ikeda', 'given': 'Ikuo'}], 'issued': {'date-parts': [[2013]]}, 'ISSN': '0453-073X', 'publisher': 'KAGAKU TO SEIBUTSU', 'container_title': 'KAGAKU TO SEIBUTSU', 'issue': '7', 'volume': '51', 'page': '483-495'}
>>> b = c.CitationStylesBibliography(s, c.source.json.CiteProcJSON([r]), c.formatter.html)
>>> b.register(c.Citation([c.CitationItem("ref0")]))
>>> str(b.bibliography()[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/citeproc/frontend.py", line 105, in bibliography
    return self.style.render_bibliography(self.items)
  File "/usr/local/lib/python3.7/site-packages/citeproc/frontend.py", line 75, in render_bibliography
    return self.root.bibliography.render(citation_items)
  File "/usr/local/lib/python3.7/site-packages/citeproc/model.py", line 244, in render
    return self.layout.render_bibliography(citation_items)
  File "/usr/local/lib/python3.7/site-packages/citeproc/model.py", line 628, in render_bibliography
    text = self.format(self.wrap(self.render_children(item)))
  File "/usr/local/lib/python3.7/site-packages/citeproc/model.py", line 569, in render_children
    text = child.render(item, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/citeproc/model.py", line 706, in render
    text, language = self.process(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/citeproc/model.py", line 720, in process
    text = self.get_macro(self.get('macro')).render(item, context)
  File "/usr/local/lib/python3.7/site-packages/citeproc/model.py", line 587, in render
    sort_options=sort_options)
  File "/usr/local/lib/python3.7/site-packages/citeproc/model.py", line 569, in render_children
    text = child.render(item, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/citeproc/model.py", line 98, in render
    return self.markup(self.process(*args, **kwargs))
  File "/usr/local/lib/python3.7/site-packages/citeproc/model.py", line 1048, in process
    text = name_elem.render(item, role, context=context, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/citeproc/model.py", line 98, in render
    return self.markup(self.process(*args, **kwargs))
  File "/usr/local/lib/python3.7/site-packages/citeproc/model.py", line 1186, in process
    given, family = format_name_parts(given, family)
  File "/usr/local/lib/python3.7/site-packages/citeproc/model.py", line 1146, in format_name_parts
    given, family = part.format_part(given, family)
  File "/usr/local/lib/python3.7/site-packages/citeproc/model.py", line 1261, in format_part
    given = self.wrap(self.format(self.case(given)))
  File "/usr/local/lib/python3.7/site-packages/citeproc/model.py", line 370, in case
    text = text.capitalize_first()
AttributeError: 'str' object has no attribute 'capitalize_first'
```

**Comment by brechtm** [comment]
`text` here should be of the `citeproc.string.String` type. Perhaps [CiteProcJSON.parse_names()](
https://github.com/brechtm/citeproc-py/blob/7ebd0d6ab983d2632acc34916c25587c20e056f4/citeproc/source/json.py#L68) should convert the values of `name_data` to `String`?

**Comment by Dreamsorcerer** [comment]
Also happens with `'associacao-brasileira-de-normas-tecnicas-ufmg-face-full'`.

**Comment by t11c** [comment]
Hi,
I had the same error, in my case it seems there was a *bug* in the csl-style which us usually ignred by other csl-processors.
I had `text-case="capitalize-first"` defined for a `number` variable (the volume number for a book) in our csl-style. Removing this for the `number` in the csl-style solved it for me.
