### ISSUE TITLE
bibtex.py crashes

### ISSUE THREAD

**Issue by mcepl** [brechtm/citeproc-py#30]
With 726bfd5 I get this (after `python setup.py develop --user` and python 2.7.5):
```
matej@mitmanek: examples (master)$ ls
bibtex.py  citeproc_json.py  xampl.bib
matej@mitmanek: examples (master)$ python bibtex.py 
/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/source/bibtex/bibtex.py:86: UserWarning: Unsupported BibTeX field 'key'
  warn("Unsupported BibTeX field '{}'".format(field))
/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/source/bibtex/bibtex.py:86: UserWarning: Unsupported BibTeX field 'organization'
  warn("Unsupported BibTeX field '{}'".format(field))
/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/source/bibtex/bibtex.py:86: UserWarning: Unsupported BibTeX field 'howpublished'
  warn("Unsupported BibTeX field '{}'".format(field))
/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/source/bibtex/bibtex.py:86: UserWarning: Unsupported BibTeX field 'type'
  warn("Unsupported BibTeX field '{}'".format(field))
/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/source/bibtex/bibtex.py:86: UserWarning: Unsupported BibTeX field 'institution'
  warn("Unsupported BibTeX field '{}'".format(field))
/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/source/bibtex/bibtex.py:86: UserWarning: Unsupported BibTeX field 'school'
  warn("Unsupported BibTeX field '{}'".format(field))
/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/source/bibtex/bibtex.py:86: UserWarning: Unsupported BibTeX field 'crossref'
  warn("Unsupported BibTeX field '{}'".format(field))
Citations
---------
Traceback (most recent call last):
  File "bibtex.py", line 69, in <module>
    print(bibliography.cite(citation1, warn))
  File "/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/frontend.py", line 102, in cite
    return self.style.render_citation(citation, self._cites, callback)
  File "/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/frontend.py", line 69, in render_citation
    return self.root.citation.render(citation, cites, callback)
  File "/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/model.py", line 239, in render
    return self.layout.render_citation(citation, callback)
  File "/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/model.py", line 619, in render_citation
    output = self.render_children(item)
  File "/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/model.py", line 582, in render_children
    text = child.render(item, **kwargs)
  File "/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/model.py", line 97, in render
    return self.markup(self.process(*args, **kwargs))
  File "/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/model.py", line 1383, in process
    child_text = child.render(item, context=context, **kwargs)
  File "/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/model.py", line 97, in render
    return self.markup(self.process(*args, **kwargs))
  File "/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/model.py", line 1383, in process
    child_text = child.render(item, context=context, **kwargs)
  File "/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/model.py", line 660, in render
    text, language = self.process(*args, **kwargs)
  File "/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/model.py", line 674, in process
    text = self.get_macro(self.get('macro')).render(item, context)
  File "/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/model.py", line 600, in render
    sort_options=sort_options)
  File "/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/model.py", line 582, in render_children
    text = child.render(item, **kwargs)
  File "/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/model.py", line 97, in render
    return self.markup(self.process(*args, **kwargs))
  File "/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/model.py", line 1090, in process
    text = substitute.render(item, context=context, **kwargs)
  File "/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/model.py", line 1299, in render
    context=context, **kwargs)
  File "/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/model.py", line 97, in render
    return self.markup(self.process(*args, **kwargs))
  File "/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/model.py", line 1060, in process
    text = name_elem.render(item, role, context=context, **kwargs)
  File "/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/model.py", line 97, in render
    return self.markup(self.process(*args, **kwargs))
  File "/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/model.py", line 1168, in process
    et_al = self.et_al()
  File "/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/model.py", line 1131, in et_al
    result = self.get_term('et-al').single
AttributeError: 'NoneType' object has no attribute 'single'
matej@mitmanek: examples (master)$
```

**Comment by brechtm** [comment]
The CSL locales were recently moved to a git submodule. You need to check out the submodules:

    git submodule update --init

If you want to validate the CSL style file (validation is on by default), you also need to generate `citeproc/data/csl.rng` from `citeproc/data/csl.rnc` (using trang for example).

**Comment by mcepl** [comment]
A way better, thank you. Although, still not perfect:
```
matej@mitmanek: examples (master)$ python bibtex.py 
/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/source/bibtex/bibtex.py:86: UserWarning: Unsupported BibTeX field 'key'
  warn("Unsupported BibTeX field '{}'".format(field))
/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/source/bibtex/bibtex.py:86: UserWarning: Unsupported BibTeX field 'organization'
  warn("Unsupported BibTeX field '{}'".format(field))
/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/source/bibtex/bibtex.py:86: UserWarning: Unsupported BibTeX field 'howpublished'
  warn("Unsupported BibTeX field '{}'".format(field))
/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/source/bibtex/bibtex.py:86: UserWarning: Unsupported BibTeX field 'type'
  warn("Unsupported BibTeX field '{}'".format(field))
/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/source/bibtex/bibtex.py:86: UserWarning: Unsupported BibTeX field 'institution'
  warn("Unsupported BibTeX field '{}'".format(field))
/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/source/bibtex/bibtex.py:86: UserWarning: Unsupported BibTeX field 'school'
  warn("Unsupported BibTeX field '{}'".format(field))
/home/matej/archiv/knihovna/repos/citeproc-py/citeproc/source/bibtex/bibtex.py:86: UserWarning: Unsupported BibTeX field 'crossref'
  warn("Unsupported BibTeX field '{}'".format(field))
Citations
---------
(Lipcoll et al. 1977)
(Knuth 1968–1990; Missilany 1984)
(Térrific 1988)
(Masterly 1988)
(Oaho et al. 1983; Ünderwood et al.)

Bibliography
------------
Lipcoll, D.J., Lawrie, D.H. & Sameh, A.H. eds., 1977. High Speed Computer and Algorithm Organization Third. D. J. Lipcoll, D. H. Lawrie, & A. H. Sameh, eds., New York: Academic Press.
Knuth, D.E., 1968–1990. The Art of Computer Programming, Addison-Wesley.
Missilany, J.-B., 1984. Handing out random pamphlets in airports.
Térrific, T., 1988. An $O(n \log n / \! \log\log n)$ Sorting Algorithm, Computer Science Department, Fanstord, California.
Masterly, É., 1988. Mastering Thesis Writing.
Oaho, A.V., Ullman, J.D. & Yannakakis, M., 1983. On Notions of Information Transfer in VLSI Circuits. In W. V. Oz & M. Yannakakis, eds. Proc. Fifteenth Annual ACM Symposium on the Theory of Computing. All ACM Conferences.  Boston: Academic Press, pp. 133–139.
Ünderwood, U., Ñet, N. & P̄ot, P., Lower Bounds for Wishful Research Results.
matej@mitmanek: examples (master)$ 
```

**Comment by brechtm** [comment]
Those fields are not listed in the BibTeX documentation, and thus they are not mapped to CSL fields.
They are just warnings and do not end up in the output. Try:

    python bibtex.py 2>/dev/null

**Comment by mcepl** [comment]
Sure
