### ISSUE TITLE
Both example scripts crash on both Python 2 and Python 3

### ISSUE THREAD

**Issue by Kodiologist** [brechtm/citeproc-py#73]
On the current HEAD (9800dad), running `citeproc_json.py` with Python 3.5.2 yields

    Citations
    ---------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/citeproc/model.py", line 1129, in et_al
        result = self.xpath_search(expr)[0].render()
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "citeproc_json.py", line 147, in <module>
        print(bibliography.cite(citation1, warn))
      File "/usr/lib/python3/dist-packages/citeproc/frontend.py", line 102, in cite
        return self.style.render_citation(citation, self._cites, callback)
      File "/usr/lib/python3/dist-packages/citeproc/frontend.py", line 69, in render_citation
        return self.root.citation.render(citation, cites, callback)
      File "/usr/lib/python3/dist-packages/citeproc/model.py", line 239, in render
        return self.layout.render_citation(citation, callback)
      File "/usr/lib/python3/dist-packages/citeproc/model.py", line 619, in render_citation
        output = self.render_children(item)
      File "/usr/lib/python3/dist-packages/citeproc/model.py", line 582, in render_children
        text = child.render(item, **kwargs)
      File "/usr/lib/python3/dist-packages/citeproc/model.py", line 97, in render
        return self.markup(self.process(*args, **kwargs))
      File "/usr/lib/python3/dist-packages/citeproc/model.py", line 1383, in process
        child_text = child.render(item, context=context, **kwargs)
      File "/usr/lib/python3/dist-packages/citeproc/model.py", line 97, in render
        return self.markup(self.process(*args, **kwargs))
      File "/usr/lib/python3/dist-packages/citeproc/model.py", line 1383, in process
        child_text = child.render(item, context=context, **kwargs)
      File "/usr/lib/python3/dist-packages/citeproc/model.py", line 660, in render
        text, language = self.process(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/citeproc/model.py", line 674, in process
        text = self.get_macro(self.get('macro')).render(item, context)
      File "/usr/lib/python3/dist-packages/citeproc/model.py", line 600, in render
        sort_options=sort_options)
      File "/usr/lib/python3/dist-packages/citeproc/model.py", line 582, in render_children
        text = child.render(item, **kwargs)
      File "/usr/lib/python3/dist-packages/citeproc/model.py", line 97, in render
        return self.markup(self.process(*args, **kwargs))
      File "/usr/lib/python3/dist-packages/citeproc/model.py", line 1060, in process
        text = name_elem.render(item, role, context=context, **kwargs)
      File "/usr/lib/python3/dist-packages/citeproc/model.py", line 97, in render
        return self.markup(self.process(*args, **kwargs))
      File "/usr/lib/python3/dist-packages/citeproc/model.py", line 1168, in process
        et_al = self.et_al()
      File "/usr/lib/python3/dist-packages/citeproc/model.py", line 1131, in et_al
        result = self.get_term('et-al').single
    AttributeError: 'NoneType' object has no attribute 'single'

(See #38 for the second error.) Running it with Python 2.7.12 yields:

    Traceback (most recent call last):
      File "citeproc_json.py", line 5, in <module>
        from citeproc.py2compat import *
    ImportError: No module named citeproc.py2compat

The other example script, `bibtex.py`, produces similar errors.

**Comment by brechtm** [comment]
The example scripts need to be run as part of the CI tests.

**Comment by Kodiologist** [comment]
In that case, I would suggest adding one or more complete standalone examples.

**Comment by yarikoptic** [comment]
py2 support is gone now in b1f0e297c43ebd8b7f809e88dbd98e9a24270679
