### ISSUE TITLE
Fails to build with python3

### ISSUE THREAD

**Issue by yurivict** [brechtm/citeproc-py#81]
Getting this error on FreeBSD 11.1 using python-3.6:
```
Assume we are running from a source distribution.
running build
running build_py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 128, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules',
  File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 74, in run
    convert_rnc()
  File "setup.py", line 67, in convert_rnc
    root = rnc2rng.load(rnc)
  File "/usr/local/lib/python3.6/site-packages/rnc2rng/__init__.py", line 4, in load
    return parser.parse(f=f)
  File "/usr/local/lib/python3.6/site-packages/rnc2rng/parser.py", line 559, in parse
    fn, src = f.name, f.read()
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 19994: ordinal not in range(128)

```

**Comment by brechtm** [comment]
Reading the file errors at the en-dash at line [677 of csl.rnc](/citation-style-language/schema/blob/master/csl.rnc#L677). I think this is a bug in [rnc2rng](/djc/rnc2rng), which opens the rnc file using the platform-default encoding. I am surprised that this is ASCII on FreeBSD, however!

I have raised an issue with rnc2rng: djc/rnc2rng#14

**Comment by brechtm** [comment]
@yurivict Can you test after applying [this patch](https://github.com/brechtm/rnc2rng/commit/a7f49b04032e624f6f86bdf59c2bbe97d79f516d) to rnc2rng? You can temporarily adjust `rnc2rng/parser.py` in your site-packages directory. Please let me know if this fixes the issue. Thanks.

**Comment by yurivict** [comment]
> Can you test after applying this patch to rnc2rng?

@brechtm It didn't help.

**Comment by brechtm** [comment]
Ah, I see where I messed up. citeproc-py will also require a small change, once rnc2rng is fixed.

**Comment by brechtm** [comment]
Can you please test with the current master branch?
