### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 35: ordinal not in range(128) 

### ISSUE THREAD

**Issue by yurivict** [brechtm/citeproc-py#84]
Build fails on FreeBSD 11.2, python 2.7:
```
===>  Building for py27-citeproc-py-0.4.0
Attempting to get version number from git...
Assume we are running from a source distribution.
running build
running build_py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 128, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules',
  File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 131, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 74, in run
    convert_rnc()
  File "setup.py", line 69, in convert_rnc
    rnc2rng.dump(root, rng)
  File "/usr/local/lib/python2.7/site-packages/rnc2rng/__init__.py", line 10, in dump
    f.write(serializer.XMLSerializer(indent).toxml(root))
  File "/usr/local/lib/python2.7/site-packages/rnc2rng/serializer.py", line 76, in toxml
    return '\n'.join(prelude + self.buf)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 35: ordinal not in range(128)
```

**Comment by yarikoptic** [comment]
Try 0.5.0 which was just released.  If still fails, please reopen and report output of `locale`.
