### ISSUE TITLE
online-currents style throws exception

### ISSUE THREAD

**Issue by Dreamsorcerer** [brechtm/citeproc-py#99]
When using the `'online-currents'` style, an exception is thrown when trying to generate the citation.

```
>>> import citeproc as c
>>> import citeproc_styles as cs
>>> s = c.CitationStylesStyle(cs.get_style_filepath("online-currents"))
>>> r = {'type': 'article', 'id': 'ref0', 'title': None, 'DOI': '10.1271/kagakutoseibutsu.51.483', 'author': [{'family': 'Ikeda', 'given': 'Ikuo'}], 'issued': {'date-parts': [[2013]]}, 'ISSN': '0453-073X', 'publisher': 'KAGAKU TO SEIBUTSU', 'container_title': 'KAGAKU TO SEIBUTSU', 'issue': '7', 'volume': '51', 'page': '483-495'}
>>> b = c.CitationStylesBibliography(s, c.source.json.CiteProcJSON([r]), c.formatter.html)
>>> b.register(c.Citation([c.CitationItem("ref0")]))
>>> str(b.bibliography()[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/citeproc/frontend.py", line 105, in bibliography
    return self.style.render_bibliography(self.items)
  File "/usr/local/lib/python3.7/site-packages/citeproc/frontend.py", line 75, in render_bibliography
    return self.root.bibliography.render(citation_items)
AttributeError: 'NoneType' object has no attribute 'render'
```

**Comment by Dreamsorcerer** [comment]
This also happens with `'bluebook-law-review'`.

**Comment by Dreamsorcerer** [comment]
Also `'public-law-review'`

**Comment by tmorrell** [comment]
I think it's because these styles don't define a bibliography. We should probably fall back to the citation definition in those cases, since that's what Zotero seems to do
